server:
  port: 8080

app:
  jjwt:
    secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave512bitsKeySize
    access_expiration: 86400
    refresh_expiration: 2592000
    tokenType: Bearer

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/metaware
    username: postgres
    password: 123
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
        non_contextual_creation: true
springdoc:
  api-docs:
    path: /v3/api-docs
